version: "3.11"

services:

    db:
      image: postgres:15.1-alpine
      container_name: db
      command: -p 5432
      expose:
        - 5432
      ports:
        - 5432:5432
      environment:
        - POSTGRES_USER=${DB_USER:?err}
        - POSTGRES_PASSWORD=${DB_PASS:?err}
        - POSTGRES_DB=${DB_NAME:?err}
      volumes:
        - postgres_db:/var/lib/postgresql/data

volumes:
  postgres_db:
